model_name: no_compress_basic_1

num_of_face: 2
vgg_face_path: ../asset/vgg_face_dag.pth

lr: 0.00003
epoch: 20
factor: 0.5
patience: 3

data_dir: /workspace2/AVS_70000/
batch_size: 2
num_workers: 8

val_every: 1
sample_for: 20
val_sample_dir: ./val_sample
save_dir: ./saved

load_model: True
load_path: ./saved/model_1.pt