model_name: baseline_1

num_of_face: 2
vgg_from_scratch: False
vgg_face_path: ../asset/vgg_face_dag.pth

lr: 0.00003
epoch: 20
factor: 0.5
patience: 3

data_dir: /workspace2/AVS_70000/
batch_size: 6
num_workers: 16

val_every: 1
save_every: 1
sample_for: 20
val_sample_dir: ./val_sample
save_dir: ./saved

load_model: True
load_path: ./saved/baseline_1/model_14.pt
load_vgg: True
load_vgg_path: ./saved/baseline_1/model_vgg_14.pt

multi_gpu: True
gpu_ids:
    - 0
    - 1