model_name: toy_100

num_of_face: 2
vgg_from_scratch: False
vgg_face_path: ../asset/vgg_face_dag.pth

lr: 0.00003
epoch: 5000
factor: 0.5
patience: 3

data_dir: /workspace2/AVS_70000/
batch_size: 1
num_workers: 8

val_every: 1
sample_for: 20
val_sample_dir: ./val_sample
save_dir: ./saved
save_every: 2000

load_model: False
load_path: ./saved/toy_100/model_0.pt
load_vgg: False
load_vgg_path: ./saved/toy_100/model_vgg_0.pt

multi_gpu: False
gpu_ids:
    - 0
    - 1